name: ne204lab0
channels:
- conda-forge
- defaults
dependencies:
- ipykernel=4.7.0
- nb_conda_kernels=2.1.0
- nbconvert=5.3.1
- nbformat=4.4.0
- matplotlib=2.1.2
- numpy=1.14.0
- pandas=0.22.0
- pytest=3.3.2
- python=3.6.4
- scipy=1.0.0
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-core==4.4.0
  - markdown==2.6.9
